"""Deepen the concise pages backed by the 38 local WAM PDFs.

Every record below was checked against the corresponding local PDF.  The two
already-long notes (RT-2 and Diffusion Policy) and the newly hand-written RT-1
note are intentionally not rewritten by this script.
"""
from html import escape
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

GROUP = {
    "latent": {
        "bridge": "这类方法的关键不是把视频压得更小，而是让相邻帧之间的变化形成可预测、可复用、最终可映射到机器人控制的 action-like 表示。",
        "signal": "检查逆模型、前向模型与策略头是否共享码本/连续潜变量，以及 latent 是否被重构损失、预测损失或动作监督共同约束。",
        "checks": ["latent action 的维度或码本大小", "是否使用 stop-gradient / EMA teacher", "人类视频与机器人轨迹的采样比例", "latent 到真实动作的适配数据量", "跨本体时是否重新训练动作解码器"],
    },
    "cascade": {
        "bridge": "级联式方法把可视未来当作中间计划，再由逆动力学、光流几何或动作策略执行；可解释性更强，但必须审计两阶段误差如何相乘。",
        "signal": "第一阶段通常由视频重构/扩散目标训练，第二阶段由动作回归或行为克隆训练。两者是否联合训练，决定视觉计划能否真正服务控制。",
        "checks": ["未来生成的时间跨度与帧率", "计划器是否看到当前机器人本体", "视觉计划到动作的标注需求", "生成失败时是否有重规划", "端到端延迟是否满足闭环频率"],
    },
    "joint_ar": {
        "bridge": "联合自回归方法把图像、状态、语言和动作安排在同一 token 序列中；真正的设计变量是 token 顺序、注意力掩码和不同模态的损失权重。",
        "signal": "视觉 token 与动作 token 往往共享 Transformer，但使用不同解码头。要确认未来视觉监督是否改善动作，而不是只成为一个占用容量的辅助任务。",
        "checks": ["各模态 token 的顺序与 attention mask", "视觉与动作损失的权重", "训练期和推理期是否都生成未来帧", "动作 chunk 长度与控制频率", "网页视频预训练如何适配机器人视角"],
    },
    "joint_diff": {
        "bridge": "联合扩散把视频和动作都视为要从噪声恢复的变量。两条流的尺度、SNR 和时间分辨率不同，因此共享去噪网络不等于自然对齐。",
        "signal": "重点核对视频/动作各自的噪声日程、条件注入、联合或分离的 velocity 目标，以及动作梯度是否能影响未来表征。",
        "checks": ["视频与动作的噪声/flow 参数化", "两模态 loss 的归一化与权重", "动作与视频时间轴如何对齐", "采样时两条流各用多少步", "是否报告只动作、只视频和联合训练消融"],
    },
    "efficiency": {
        "bridge": "效率工作必须在同一硬件、同一预测长度和同一成功率口径下讨论；只报 FLOPs 或单层速度不能证明机器人闭环真正变快。",
        "signal": "蒸馏、稀疏 token 或缓存近似都应保留原 WAM 的条件分布。除了逼近教师，还要检查误差是否随连续 action chunk 累积。",
        "checks": ["延迟是否含视觉编码与 VAE", "硬件、精度和 batch size", "视频与动作分别使用的采样步数", "加速前后闭环成功率", "长序列误差与缓存失效策略"],
    },
    "multimodal": {
        "bridge": "力觉与触觉的价值不是多一个输入，而是提供视觉不可观测的接触状态，并把预测—实测差异变成执行期反馈。",
        "signal": "核对传感器时间同步、模态编码器、未来接触预测和残差控制器的监督来源；离线预测准确并不自动等于接触闭环稳定。",
        "checks": ["视觉与力/触觉的采样率和同步", "传感器标定与归一化", "缺失或饱和模态的退化策略", "预测接触如何进入动作头", "是否在扰动和未见物体上闭环评测"],
    },
    "real2sim": {
        "bridge": "Gaussian Splatting 解决照片级渲染，physics engine 解决碰撞与动力学；两者必须通过相机、机器人和可动物体坐标系严密配准。",
        "signal": "重建损失只保证像素，不保证接触。审计时要分开看外观拟合、几何/资产提取、物理参数和最终 sim-to-real 策略证据。",
        "checks": ["采集视角数量与重建时间", "splat、mesh 和碰撞体如何对齐", "机器人/可动物体怎样从背景分离", "物理参数是否需要真机标定", "是否真正零样本部署而非再微调"],
    },
    "benchmark": {
        "bridge": "评测论文不训练策略，却决定哪些‘世界模型’主张可被证伪。关键是把视觉质量、物理规律、动作可控性和下游可用性拆开。",
        "signal": "基准的学习信号来自人工标注、规则指标、视觉模型或 MLLM judge。必须报告与人类偏好的相关性，并防止 judge 被画质或提示词表面特征误导。",
        "checks": ["样本与提示词如何构造", "物理维度是否覆盖因果反事实", "人类标注协议与一致性", "自动 judge 的校准与泄漏风险", "最终分数是否掩盖维度间权衡"],
    },
}

# thesis, four pipeline stages, paper-specific training point, three evidence
# rows, comparison, limitations, short verbatim abstract quote.
P = {
"flash-wam": ("efficiency", "同一 WAM 的视频流和动作流处在不同 SNR 分布，Flash-WAM 因而分别选择 consistency 参数化，而不是把单模态蒸馏直接复制两遍。", ["从多步 joint video-action diffusion 教师出发，冻结其任务定义与条件。", "统计视频流和动作流在各噪声区间的边际分布与 SNR 偏移。", "为两种模态选择不同 consistency function，并做 modality-aware distillation。", "以极少视频/动作步联合采样，再核对动作成功率是否保留。"], "训练目标必须同时约束学生与教师的一致性、视频高噪声稳定性和动作低噪声精度；共享一个时间权重会让一条流主导梯度。", [("速度", "L40S 上比较不同视频/动作步数组合", "最高报告约 23× 加速，但应和成功率一起读"), ("控制", "LIBERO / LingBot-VA 设置", "少步采样仍需保持闭环任务表现"), ("消融", "统一与分模态蒸馏参数化", "验证收益来自噪声分布适配而非只减步")], "它与 Fast-WAM 的差别是：Flash-WAM仍在推理时生成两条流，只是把去噪链蒸馏得更短；Fast-WAM更进一步质疑测试时是否需要显式未来想象。", ["教师模型偏差会被一起蒸馏", "极少步下视频可读性和动作精度可能出现不同最优点", "硬件 kernel 与 VAE 开销会缩小理论加速"], "World-action models jointly generate future video and robot actions through iterative diffusion."),
"videophy": ("benchmark", "VideoPhy 用日常物体交互提示词检查生成视频是否遵守重力、碰撞、支撑与材料行为，把‘看起来真’和‘物理过程对’分开。", ["收集包含明确物体关系与可判定物理结果的文本提示。", "对多个视频生成模型按相同提示采样。", "人工分别标注语义遵循与物理常识遵循。", "训练/校准自动评估器，并与人类判断相关性对齐。"], "自动指标不是对视频做通用美学打分，而要识别交互是否按物理规则发展；因此语义一致性和物理一致性必须分头报告。", [("内容", "多类日常物理交互提示", "避免只测自由落体这一类简单规律"), ("对照", "不同规模和训练方式的视频模型", "画质提升不保证物理遵循同步提升"), ("评估", "人工标注与自动 judge", "先验证相关性，再使用自动分数扩展评测")], "VideoPhy 比 FVD 更接近 world-model 问题，但仍主要是被动观察；WorldSimBench 进一步加入 embodied/操控视角，WorldModelBench则强调应用域与 instruction following。", ["短片可能在结果发生前结束", "提示词本身可能含糊或多解", "自动 judge 易被逼真纹理掩盖错误动力学"], "We present VideoPhy, a benchmark designed to assess whether the generated videos follow physical commonsense."),
"motus": ("latent", "Motus 不再把理解、未来预测和控制拆成多个模型，而是学习可在视频与机器人数据间共享的 latent action，再由统一模型完成后果预测与动作生成。", ["编码当前观测、语言与目标，形成共享多模态上下文。", "从相邻帧/轨迹中提取 embodiment-agnostic latent action。", "用 latent action 条件化未来建模，同时学习机器人动作映射。", "在不同本体上重用世界动态，只对控制接口做适配。"], "核心是让 latent action 同时解释视觉变化并对真实动作有预测力；若只优化重构，它可能吸收相机运动和背景变化。", [("仿真", "RoboTwin 2.0 的 clean 与 randomized 多任务设置", "检验跨场景鲁棒性而非只记训练背景"), ("真机", "AC-One 双臂平台上的操作任务", "验证 latent 到动作映射能够落地"), ("消融", "统一建模对比隔离式 VLA / world model", "判断共享表示是否真的带来正迁移")], "与 villa-X 相比，Motus更强调把后果预测和动作生成统一；与 LAPA 相比，它不只把 latent action 当预训练标签，而要把它放入完整 world-action loop。", ["latent 仍可能纠缠相机与本体运动", "跨本体共享程度受观测空间对齐限制", "长程 rollout 会放大 latent dynamics 误差"], "We propose Motus, a unified latent action world model."),
"genie": ("latent", "Genie 证明无动作标签的互联网视频也能训练可交互环境：latent action model 从帧间变化中发现控制码，dynamic model 再按这些码自回归生成未来。", ["C-ViViT tokenizer 将视频帧压成离散时空 token。", "latent action model 由连续帧反推动作码，并限制码本容量。", "dynamics model 在过去 token 和 latent action 条件下预测下一帧 token。", "部署时用户选择 latent code，模型持续滚动生成可玩的世界。"], "LAM 的瓶颈迫使代码表达可控变化；但没有真实动作标签时，代码编号没有固定语义，只能通过交互或少量标注解释。", [("数据", "大规模 2D platformer 视频", "从行为视频而非引擎动作学习"), ("生成", "长程自回归世界一致性", "检查角色、场景与碰撞是否随 rollout 漂移"), ("控制", "latent action 可控性与人类可玩性", "好视频不等于动作码可稳定复用")], "Genie 是 latent-action world model 的起点；LAPA把类似思想迁移到 VLA 预训练，villa-X/Motus继续改善动作语义与跨本体落地。", ["动作码可能纠缠角色、相机与场景变化", "自回归误差会让长程世界崩坏", "平台游戏的离散动力学不能直接外推到接触操作"], "We introduce Genie, the first generative interactive environment trained in an unsupervised manner from unlabelled Internet videos."),
"worldvla": ("joint_ar", "WorldVLA 将 VLA 与 world model 放进单个自回归框架，让动作生成既读取当前视觉语言上下文，也受到未来图像 token 监督。", ["视觉编码器把当前图像与语言映射为统一上下文。", "自回归主干交织建模图像 token 与动作 token。", "world branch 预测未来图像，action branch 预测动作序列。", "推理时按设定选择显式生成未来或直接读取动作头。"], "联合目标要平衡图像 token 交叉熵与动作损失；视觉分支过强会消耗容量，过弱又无法给控制提供动力学先验。", [("基准", "通用操作仿真与真机任务", "同时检查已见任务和分布外组合"), ("世界建模", "未来图像质量/一致性", "只作为中间证据，不能替代成功率"), ("消融", "移除未来预测或改变 token 组织", "确认控制增益来自 world objective")], "GR-1/GR-2同样联合预测图像与动作；WorldVLA的研究重点是统一自回归 action-world 序列，而 CoT-VLA更强调先生成显式视觉 goal 再生成短动作块。", ["自回归视觉 token 增加推理延迟", "未来图像与动作可能分别正确却因时间错位不一致", "网页视觉先验到机器人视角仍有域差"], "WorldVLA integrates Vision-Language-Action model and world model in one single framework."),
"gr-2": ("joint_ar", "GR-2 先用 3800 万互联网视频片段和 500 亿 token 学世界动态，再在机器人轨迹上联合微调视频生成与动作预测。", ["将 Internet 视频离散成时空 token，做大规模生成式预训练。", "加入语言、机器人状态与历史观测形成统一条件。", "机器人微调阶段同时预测未来画面和低层动作。", "闭环执行动作，并用新任务/新场景评测预训练迁移。"], "预训练学到的是通用视觉动态，机器人微调负责把这些动态绑定到可执行动作；联合损失是避免 world prior 与控制头脱节的关键。", [("规模", "38M clips / 50B tokens 视频预训练", "证明收益建立在大规模 world prior 上"), ("多任务", "100+ 机器人任务", "报告平均成功率并检查任务间干扰"), ("泛化", "未见物体、场景和任务组合", "区分训练任务记忆与真正迁移")], "GR-1建立联合视频—动作预训练范式，GR-2把数据与模型规模显著放大；WorldVLA和CoT-VLA则探索不同的自回归 token 组织与视觉推理顺序。", ["数据规模使小团队难以复现", "生成未来的收益可能与更大 backbone 混杂", "3 Hz/低频视觉生成仍可能限制精细接触"], "GR-2 is first pre-trained on a vast number of Internet videos to capture the dynamics of the world."),
"villa-x": ("latent", "villa-X 同时改造 latent action model 和其进入 VLA 的方式，使隐动作不仅能重构帧间变化，还能形成零样本动作计划并适配不同本体。", ["LAM 从帧对提取动作相关 latent，而非直接回归机器人坐标。", "通过结构约束提高 latent 的时间与语义可分性。", "Actor 模块把观测、语言与 latent plan 映射到真实 action chunk。", "先利用大规模无动作视频，再用较少机器人数据落地。"], "要分别检查 LAM 的表示目标与 Actor 的控制目标；只有当 latent 计划在未见本体/语言下仍有结构，视频预训练才真正提供额外信息。", [("latent 质量", "零样本计划与可视化/检索", "判断码是否对应动作而非外观"), ("仿真", "SIMPLER 等分布外任务", "检验跨场景与跨本体"), ("真机", "夹爪与灵巧手两类平台", "验证同一 latent prior 能否由不同 actor 解码")], "LAPA使用离散 latent action 作为 VLA 预训练标签；villa-X进一步优化 latent 的规划能力与接入方式；Motus则把 latent action、world prediction和control统一得更彻底。", ["latent 语义仍可能依赖视频拍摄方式", "actor 适配需要足够本体数据", "零样本 latent plan 不等价于零样本真实控制"], "We introduce villa-X, a novel Vision-Language-Latent-Action framework."),
"unipi": ("cascade", "UniPi 把文本条件控制写成视频生成问题：先合成完成任务的未来帧，再从相邻帧变化中提取动作。", ["语言指定目标，当前观测提供视频生成起点。", "文本条件视频扩散模型生成候选未来轨迹。", "逆动力学/任务适配器把帧间变化翻译成环境动作。", "执行短段动作后重新观测并滚动规划。"], "视频模型由无动作视频学习可行状态演化，动作模块由少量带动作数据学习接口；两阶段数据需求不同，这是它可利用大规模视频的原因。", [("多域", "不同控制环境与文本任务", "验证统一视频 planner 的迁移"), ("规划", "候选视频与目标一致性", "看生成是否提供可执行中间状态"), ("控制", "任务回报/成功率", "最终证据必须来自动作闭环")], "UniPi是显式级联的清晰原型；AVDC把动作提取变成稠密对应几何，Vidar用 masked inverse dynamics增强跨本体适配。", ["第一阶段幻想不可达状态会误导控制器", "视频采样慢于直接 policy", "逆动力学在遮挡或多解动作下不唯一"], "We cast the sequential decision making problem as a text-conditioned video generation problem."),
"worldscore": ("benchmark", "WorldScore 将 3D、4D 和视频生成统一成带相机轨迹约束的 next-scene generation，再从视觉质量、几何一致和可控运动等维度评分。", ["把连续世界生成切成明确布局与相机轨迹的下一场景任务。", "构建覆盖静态/动态、室内/室外、真实/风格化的 3000 个样例。", "按可控性、质量与动力学等维度计算指标。", "用人类偏好检验总分与分维度分数是否可靠。"], "这里的‘监督’是评测协议：相机路径提供可验证的空间约束，多维 metric 避免单一美学分数掩盖世界结构错误。", [("覆盖", "3000 examples、多种世界类型", "减少只针对单一生成范式的偏差"), ("统一", "3D/4D scene 与 video model", "同一 next-scene 接口才能横向比较"), ("相关性", "自动指标与人工判断", "总分有效前必须通过人类校准")], "WorldScore关注可导航世界生成的统一接口；VideoPhy/Physics-IQ更聚焦物理规律，WorldModelBench更聚焦应用域中的指令与物理违例。", ["next-scene 任务仍短于长期交互", "总分权重会隐藏不同能力侧重", "相机可控不等于物体受动作可控"], "We introduce the WorldScore benchmark, the first unified benchmark for world generation."),
"gaussgym": ("real2sim", "GaussGym 把 3DGS 作为 Isaac Gym 等向量化物理仿真的 drop-in renderer，在保持并行 RL 吞吐的同时提供真实场景外观。", ["用手机/数据集扫描重建场景 Gaussian splats。", "将 splat 外观与物理引擎中的碰撞几何和机器人状态配准。", "在数千并行环境中实时渲染策略观测。", "训练视觉 locomotion policy，并零样本部署到对应真实场景。"], "策略仍由 RL 奖励训练；3DGS改变的是观测分布，不替代动力学。复现要确保渲染相机位姿随仿真机器人状态实时更新。", [("吞吐", "4096 parallel envs / consumer GPU", "报告超过 100k steps/s，需注明分辨率"), ("语义", "避开不适宜区域等视觉导航", "检验 RGB 语义是否比深度提供额外价值"), ("迁移", "扫描真实环境后的 sim-to-real", "确认测试时没有真机视觉微调")], "SplatSim面向机械臂操作与可动物体，GaussGym面向大规模视觉 locomotion；GSWorld进一步提供闭环数据纠错与评测套件。", ["外观真实不修复错误摩擦/接触", "扫描质量与光照变化影响迁移", "高吞吐数字依赖分辨率、并行数和GPU"], "We integrate 3D Gaussian Splatting as a drop-in renderer within vectorized physics simulators."),
"vidar": ("cascade", "Vidar 把互联网规模视频扩散模型作为跨本体视觉先验，再用 masked inverse dynamics model 从预测视频中恢复当前机器人动作。", ["统一不同平台的多视角观测表示，持续预训练 video diffusion。", "以当前观测与语言生成短期 embodied future。", "MIDM对视角/时间做mask，学习从视觉变化恢复动作。", "新本体只需适配 inverse dynamics，而不是重训全部视频先验。"], "750K multi-view trajectories用于把网络视频 prior 拉到机器人域；MIDM 的 mask 迫使模型利用跨视角动态而非记住单一背景。", [("预训练", "三种真实平台、750K 多视角轨迹", "检查规模与本体多样性"), ("泛化", "背景与视角扰动", "针对 pixel-to-action 易退化的问题"), ("跨本体", "不同机器人平台", "验证 video prior 与动作 adapter 的解耦")], "与UniPi相比，Vidar使用更强的 embodied video prior和masked IDM；与联合式 WAM 相比，它保留清晰的视觉计划—动作适配接口。", ["未来视频采样延迟仍高", "IDM在多解动作时可能平均化", "统一观测空间不保证动力学真正共享"], "Vidar consists of an embodied video diffusion model and a masked inverse dynamics model."),
"pad": ("joint_diff", "PAD 注意到视频预测与动作扩散都在做去噪，于是让未来图像和动作在同一 denoising process 中相互约束。", ["对未来图像与 action chunk 分别加噪。", "共享视觉语言条件，并保留模态专用输入/输出头。", "一次网络前向同时预测图像与动作的去噪方向。", "推理时联合采样或读取动作流完成闭环。"], "联合损失既是多任务正则，也是动力学耦合；要通过只预测动作、只预测图像和两者联合的消融确认增益。", [("数据效率", "较少演示的 imitation setting", "检验未来预测是否提供额外监督"), ("基准", "多任务操作仿真/真机", "不能只用图像指标证明策略有效"), ("消融", "共享/分离模块与预测 horizon", "判断耦合发生在哪一层")], "PAD是Joint-Diffusion早期代表；UWM更系统地为视频与动作设置独立扩散并耦合，UVA则处理两模态时空分辨率不匹配。", ["联合采样计算昂贵", "视频loss可能压过低维动作loss", "好看的未来不保证动作因果一致"], "We introduce PAD, a novel visual policy learning framework via a joint denoising process."),
"fawam": ("multimodal", "FAWAM在感知、预测与执行三层使用六轴力/力矩：历史 wrench 调制动作，模型预测未来 wrench，残差控制器再用预测—实测误差闭环修正。", ["同步编码视觉、机器人状态与历史六轴 wrench。", "force-conditioned action model 生成 nominal action chunk。", "联合预测未来动作与末端 wrench trajectory。", "执行时 residual module 比较预期与实测 wrench 并修正动作。"], "世界模型损失不只预测RGB，还显式监督接触力演化；残差模块把未来力预测从辅助任务变成可执行反馈。", [("任务", "插接、擦拭等 contact-rich manipulation", "覆盖力变化决定成败的任务"), ("扰动", "物体偏移/接触条件变化", "检验 residual 是否真的闭环纠偏"), ("消融", "仅force输入、force预测、residual correction", "分离三层设计各自贡献")], "OmniVTA用触觉图像和60Hz reflex，FAWAM用六轴wrench并显式预测力轨迹；两者共同说明多模态WAM的重点是预测参考而非简单拼接。", ["传感器零漂与饱和会污染残差", "不同末端执行器的wrench分布难直接迁移", "残差幅度过大可能破坏基座动作"], "FAWAM incorporates force information at three levels: perception, prediction, and closed-loop execution."),
"vpp": ("cascade", "VPP把video diffusion的中间/预测表征当作generalist policy的视觉先验，再由动作扩散头生成控制，不要求部署时完整渲染高质量视频。", ["用video prediction pretraining学习含动态信息的视觉编码器。", "从历史观测提取 predictive visual representations。", "动作扩散头在语言、状态和视觉表征条件下去噪 action chunk。", "闭环执行时复用预测表征，而非只用静态图像特征。"], "视频预训练提供动态监督，动作头由机器人演示监督；最关键的对照是同一动作头配静态预训练编码器。", [("表征", "重建、对比与video prediction预训练", "隔离动态预训练的价值"), ("多任务", "generalist manipulation benchmarks", "检查任务间共享而非单任务拟合"), ("鲁棒性", "视觉扰动和未见场景", "验证predictive representation是否减小分布偏移")], "VPP位于显式视频规划和纯reactive policy之间：它吸收video model的hidden representation，但不必先生成可观看未来再做IDM。", ["表征提升可能来自更大预训练数据", "隐式未来难以人工诊断", "动作头仍受演示覆盖限制"], "Video diffusion models inherently produce predictive representations that benefit embodied tasks."),
"gsworld": ("real2sim", "GSWorld把真实场景重建、Gaussian Scene asset、物理交互和policy评测连成闭环，使真实数据训练的策略能在可复现数字副本中纠错与再训练。", ["扫描真实场景并分离背景、机器人与可动物体。", "构建同时包含Gaussian外观与物理属性的GSDF资产。", "在physics engine中闭环渲染相机观测与对象运动。", "用sim DAgger/评测补充真实策略，再回到真机验证。"], "GSDF 的优化包含外观重建，但策略改进来自仿真中的纠正轨迹；必须区分renderer质量与DAgger数据贡献。", [("重建", "多类真实操作场景", "检查新视角与动态对象的渲染稳定性"), ("策略", "Place Box、Stack/Arrange Cans等任务", "比较真实纠正与仿真纠正数据"), ("闭环", "sim-to-real与real-policy-in-sim", "验证数字副本既能训练也能评测")], "SplatSim强调零样本RGB策略迁移，GSWorld更重视closed-loop suite和纠错数据，GaussGym则强调向量化locomotion吞吐。", ["资产构建仍含人工分割/标定成本", "视觉一致不代表接触参数一致", "策略可能利用重建伪影"], "GSWorld combines 3D Gaussian Splatting with physics engines for closed-loop manipulation."),
"avdc": ("cascade", "AVDC从动作无标注视频生成未来，再用稠密对应、深度与几何闭式解算机器人动作，尽量避免训练昂贵IDM。", ["文本条件video model合成机器人完成任务的短视频。", "估计相邻帧的dense correspondence / optical flow。", "结合深度把二维像素位移提升为三维末端变化。", "执行几何动作并重新拍摄，循环直到目标完成。"], "视频生成由actionless data提供监督；动作恢复依赖视觉对应和相机几何，而不是每段视频的动作标签。", [("少样本", "few video demonstrations", "检查是否真的不需要动作标注"), ("跨环境", "不同机器人与场景", "验证图像表示的task-agnostic属性"), ("几何", "flow/depth/action模块消融", "定位失败来自生成还是对应估计")], "UniPi通常训练动作提取器，AVDC更依赖dense correspondence的几何闭式解；Vidar则回到learned masked IDM以提升复杂场景适配。", ["遮挡和弱纹理使对应失效", "深度误差会直接放大为三维动作误差", "生成视频中的非刚体变化不一定可由机器人执行"], "Our method executes diverse tasks from few video demonstrations without any action annotations."),
"uva": ("joint_diff", "UVA针对video高空间分辨率、action高时间分辨率的冲突，使用统一sequence model但保留两条不同tokenization与diffusion路径。", ["视频帧压成低时间率、高空间信息的latent token。", "动作轨迹切成高时间率、低维action token。", "共享时序Transformer进行跨模态attention。", "各模态按自己的noise level去噪，并通过共同上下文耦合。"], "训练时不能简单逐帧对齐；UVA通过异步/多率表示让视频提供场景动力学，动作保留细粒度控制。", [("策略", "LIBERO10等操作任务", "比较联合预训练与直接policy"), ("预测", "视频与轨迹生成质量", "确认两条流均未坍缩"), ("结构", "统一模型对比解耦video/action diffusion", "检验跨模态attention贡献")], "UWM强调coupled diffusion objective，UVA强调同一模型内的时空分辨率不匹配；PAD是更早的joint denoising原型。", ["多率对齐增加实现复杂度", "视频token仍可能占大部分算力", "训练期联合生成不保证推理期低延迟"], "A unified video and action model holds significant promise for robotics."),
"worldmodelbench": ("benchmark", "WorldModelBench把视频模型放进机器人与自动驾驶等应用域，从instruction following和physics adherence两轴检查细微世界建模违例。", ["构建带参考条件与应用语义的生成任务。", "将违例拆成指令不服从和物理不遵守。", "收集人类对成对视频的细粒度判断。", "训练/选择world-modeling judger并校准到人类偏好。"], "judge必须对‘画质高但动作/物理错’保持敏感；论文因此不直接沿用通用video quality metric。", [("领域", "robotics与autonomous driving场景", "让评测和决策应用发生联系"), ("细粒度", "instruction与physics violation", "避免美学分数掩盖关键错误"), ("可靠性", "judge与human correlation", "检查自动评估器是否稳定排序")], "VideoPhy用日常物理提示，WorldModelBench强调应用驱动场景，WorldSimBench还加入由视频推断动作/操控的隐式评测。", ["judger可能继承VLM偏差", "参考条件不一定覆盖所有合理未来", "短视频评测难发现长期因果漂移"], "Current benchmarks focus on general video quality while ignoring physics adherence."),
"dreamzero": ("joint_diff", "DreamZero把预训练video diffusion backbone变成joint video-action WAM，核心主张是未来世界预测能带来VLA缺乏的未见运动零样本泛化。", ["从大规模video diffusion backbone初始化world prior。", "统一异构机器人数据的观测、语言与动作接口。", "联合去噪未来视频latent和action chunk。", "通过系统优化达到可闭环频率，并在新任务/新环境零样本执行。"], "视频预测提供密集动力学监督，动作流将world prior绑定到控制；真正的因果证据来自相同robot data下与VLA对照。", [("泛化", "新任务、新环境与未见motion", "论文报告相对强VLA超过2×"), ("异构数据", "多来源机器人轨迹", "检查是否减少重复演示依赖"), ("真机", "多种真实操作任务", "零样本口径必须排除任务微调")], "它与LingBot-VA都从video world modeling出发：DreamZero强调zero-shot motion generalization，LingBot-VA强调因果分解与自回归diffusion架构。", ["video backbone的物理偏差会传给动作", "零样本任务仍受语言与观测接口限制", "联合采样的实时化依赖系统工程"], "State-of-the-art VLA models excel at semantics but struggle with unseen physical motions."),
"lingbot-va": ("joint_diff", "LingBot-VA把未来想象拆成具有因果方向的三步自回归过程：先由当前状态和动作生成未来，再让未来约束后续动作，从而避免把video loss仅当无关辅助任务。", ["以当前图像、语言和机器人状态建立因果上下文。", "autoregressive diffusion先预测动作条件的近未来视觉状态。", "动作分支读取当前表征与future imagination生成action chunk。", "执行后用新观测重新启动短期因果rollout。"], "训练同时包含conditional flow matching的视频生成与动作目标；注意力mask和条件顺序决定模型学的是动作导致未来，还是仅利用数据相关性猜未来。", [("大规模预训练", "通用视频与机器人数据的分阶段训练", "检查world prior怎样迁移到控制"), ("真机", "多任务robot manipulation", "比较reactive VLA与联合world-action训练"), ("因果消融", "移除future、改变生成顺序或条件", "确认未来表征是动作原因链的一部分")], "DreamZero强调未见motion的zero-shot policy，LingBot-VA更强调causal world modeling和autoregressive diffusion；WorldVLA则用自回归token而非连续flow组织两种模态。", ["注意力顺序只能施加结构偏置，不能自动保证真实因果", "想象错误会反向污染动作分支", "完整视频生成仍带来闭环延迟"], "Video world models imagine the near future by understanding causality between actions and visual dynamics."),
"efficient-wam": ("efficiency", "Efficient-WAM用1B模型、从WAN迁移的compact video expert、token-sparse video latent和非对称去噪，把未来想象的成本集中压缩。", ["从WAN-2.2-5B迁移动态知识到更小video expert。", "只保留控制相关的稀疏video token，而非完整高保真帧。", "video与action分配不同网络容量和denoising预算。", "联合训练后在少步想象下输出action chunk。"], "非对称设计承认视频与动作的难度/带宽不同；训练要保证压缩后的video latent仍携带对控制有用的后果信息。", [("规模", "1B parameter WAM", "和大模型比较时同时报告数据与预训练来源"), ("效率", "latency/FLOPs/显存", "确认收益不是降低分辨率后只测单模块"), ("控制", "sim与real manipulation", "质量—速度Pareto最终由成功率决定")], "Flash-WAM压缩采样步数，C3ache复用跨chunk计算，Efficient-WAM则从模型、token与两流预算三个层面重做轻量架构。", ["教师迁移可能带来domain bias", "稀疏token会遗漏细小接触变化", "1B仍可能超出板载实时预算"], "Efficient-WAM reduces the cost of future imagination while preserving its control benefit."),
"physics-iq": ("benchmark", "Physics-IQ不问单个视频是否顺眼，而用成组实验和可计算物理量检查模型是否稳定遵守质量、速度、碰撞等规律。", ["为同一物理原则构造受控场景与参数变化。", "对视频模型进行多次采样，减少偶然正确。", "从生成帧提取轨迹/空间关系等可测量量。", "汇总为Physics-IQ并和人类/MLLM评估比较。"], "指标强调跨条件的一致规律，而不是一条样本的像素相似；只有趋势随干预正确变化，才能支持‘学到物理’。", [("原则", "多类基础物理规律", "区分记忆常见视频与组合推理"), ("模型", "主流T2V/I2V系统", "检验规模增长是否带来规律提升"), ("评估", "程序化、human与MLLM", "分析自动judge是否高估逼真视频")], "VideoPhy以自然语言活动为单位，Physics-IQ更强调受控变量和量化规律；二者都提醒WAM不能把photorealism当physics。", ["视觉测量误差会污染物理量", "生成模型可能靠数据先验猜中结果", "短时基础规律不覆盖复杂接触控制"], "Do video models learn world models that discover laws of physics?"),
"worldsimbench": ("benchmark", "WorldSimBench先给predictive model分能力层级，再组合显式感知评估与隐式操控评估，测试视频能否支持embodied decision。", ["按输入条件和输出能力定义predictive model层级。", "显式评估语义、视觉质量、时间与物理一致性。", "隐式评估从生成结果恢复动作或完成操控任务。", "结合human preference和自动指标形成双重证据。"], "隐式操控是关键：若生成视频真的保存动作相关动力学，IDM或操控评估应能从中恢复可用信息。", [("显式", "层级化视觉/物理维度", "定位具体能力而非只给总分"), ("隐式", "manipulative evaluation", "把视频质量连接到embodied usefulness"), ("对照", "不同类别predictive models", "避免能力等级不同却直接横比")], "相较WorldModelBench的application-domain judge，WorldSimBench显式加入manipulative evaluation，更接近‘视频是否可作为policy planner’。", ["下游IDM自身误差会混入模型评分", "层级边界可能随模型能力变化", "隐式任务仍未等同真实机器人闭环"], "We propose a dual evaluation framework called WorldSimBench."),
"splatsim": ("real2sim", "SplatSim用Gaussian splats替代传统纹理mesh渲染，再把机器人和可动物体与physics simulation对齐，目标是RGB manipulation policy零样本sim-to-real。", ["采集真实场景多视角图像并训练背景/物体3DGS。", "为机器人关节与可动物体建立可变换splat资产。", "将视觉资产绑定到模拟器的collision和kinematics。", "只在SplatSim渲染观测上训练policy，再直接部署真机。"], "policy由仿真演示/行为克隆监督；3DGS的作用是缩小RGB域差。必须保持仿真状态和splat变换严格同步。", [("渲染", "真实场景新视角", "验证splat外观而非只看训练视角"), ("策略", "多种manipulation tasks", "比较mesh/domain randomization/GS rendering"), ("迁移", "zero-shot real deployment", "不允许用真实动作数据补偿视觉差")], "SplatSim是GS real-to-sim操作基线；GSWorld扩展为闭环策略开发套件，GaussGym证明向量化GS渲染也能支撑locomotion RL。", ["透明/反光与强光变化仍难重建", "碰撞几何通常不是由splat自动得到", "动态对象分离和关节标定需要人工工程"], "SplatSim leverages Gaussian Splatting as the primary rendering primitive to reduce the Sim2Real gap."),
"himem-wam": ("efficiency", "HiMem-WAM将低层motion latent、高层skill latent和边界触发memory结合，避免每一时刻都向长序列写入冗余视觉状态。", ["低层latent action编码短时运动。", "高层skill latent对长动作片段形成时间抽象。", "boundary predictor检测技能切换，只在边界写入compact memory。", "当前观测检索层次记忆，联合生成未来与动作。"], "除了world/action loss，还要监督层次latent与边界门控；若boundary预测失准，记忆会漏写关键状态或被冗余填满。", [("长程", "多阶段simulation manipulation", "比较无记忆、逐帧记忆和边界记忆"), ("真机", "需要回忆早期状态的任务", "验证记忆不只是benchmark trick"), ("效率", "memory长度、显存和成功率", "检查压缩是否真降低长程成本")], "C3ache缓存短期重复计算，HiMem-WAM保存任务级语义状态；二者都复用过去，但一个面向推理冗余，一个面向长期信用与状态记忆。", ["skill boundary标注/学习可能不稳定", "错误记忆会持续污染后续规划", "任务结构变化会破坏已学skill abstraction"], "HiMem-WAM integrates motion-centric latent actions, high-level skill latents, and boundary-triggered memory updates."),
"vla-jepa": ("latent", "VLA-JEPA不要求生成未来像素，而在latent空间预测未来状态；同时学习latent action与flow-matching动作头，把world loss直接作为VLA表征约束。", ["online encoder提取当前观测latent，target encoder产生未来目标latent。", "latent action模块描述从当前到未来的可控变化。", "predictor在语言/状态/latent action条件下预测future embedding。", "flow-matching action head把动作latent映射为真实action chunk。"], "JEPA loss使用target/online分支并需防坍缩，action flow loss负责控制；关键是future latent只保留任务相关可预测信息。", [("仿真", "LIBERO与LIBERO-Plus", "检查分布外语言、对象与场景"), ("真机", "Franka manipulation", "验证latent world model可闭环"), ("消融", "world loss、latent action与flow head", "区分表征和动作生成贡献")], "FLARE同样做future latent alignment但改动更轻；VLA-JEPA更明确构建JEPA world model和latent action；像素WAM则付出生成成本换可视未来。", ["latent预测不可直接人工判断物理错误", "target encoder/EMA设置会影响坍缩", "latent action是否跨本体仍需更多证据"], "VLA-JEPA enhances a Vision-Language-Action model with a latent world model."),
"gr-1": ("joint_ar", "GR-1用GPT式序列模型联合预测未来图像、机器人动作和状态，是大规模video generative pretraining迁移到机器人控制的早期代表。", ["在大规模视频上预训练时空生成能力。", "将语言、历史图像与机器人state编码为序列token。", "共享Transformer同时预测future image token与action/state。", "在机器人数据上微调并以短时闭环滚动执行。"], "视频预训练目标学习动态与语义，机器人微调的动作/状态损失把这些表征绑定到控制。要看未来预测loss在微调后是否继续保留。", [("仿真", "CALVIN等多任务长程设置", "评估语言条件技能与序列组合"), ("真机", "多类桌面操作", "验证视频预训练不只提升离线指标"), ("消融", "有/无video pretraining及future prediction", "分开数据和辅助任务贡献")], "GR-1建立联合AR基线，GR-2将Internet视频规模扩到38M clips并覆盖100+任务；WorldVLA继续研究统一token序列。", ["像素预测占用大量模型容量", "GPT式误差会随未来token自回归累积", "机器人动作频率受视觉序列吞吐限制"], "GR-1 predicts robot actions as well as future images in an end-to-end manner."),
"lapa": ("latent", "LAPA先用VQ-VAE从帧对量化离散latent action，再让VLA在无动作视频上预测这些token，最后用少量机器人动作数据完成语义对齐。", ["训练action quantizer，把两帧变化压成离散code。", "在Internet/人类视频上以观测和任务描述预测latent action。", "用forward reconstruction确保code能解释未来变化。", "在小规模机器人数据上将latent-pretrained VLA微调为真实动作策略。"], "VQ瓶颈决定code容量；commitment/reconstruction与latent prediction共同防止code忽略动作或记住像素细节。", [("预训练", "大规模无动作视频", "核心变量是视频量和动作多样性"), ("下游", "多种robot manipulation benchmark", "与只用机器人动作预训练的VLA对照"), ("消融", "码本、视频来源与机器人微调量", "确认少量动作数据如何解码latent prior")], "Genie证明无标注视频可学可控code，LAPA将其变成VLA预训练标签；villa-X与Motus继续提升code语义与统一建模。", ["code可能表示相机运动而非可执行动作", "离散码本容量过小会合并不同控制", "最终仍需要带动作机器人数据对齐"], "We introduce Latent Action Pretraining without ground-truth robot action labels."),
"cot-vla": ("joint_ar", "CoT-VLA先自回归生成未来图像作为visual chain-of-thought，再生成短action chunk，让中间视觉goal承担显式时间规划。", ["编码当前图像、语言与机器人状态。", "自回归预测一个或多个future image token/latent。", "混合attention让动作读取当前上下文与visual CoT。", "动作头生成短chunk，执行后重新规划。"], "视觉CoT和动作loss共同训练；需要控制teacher forcing差异，否则训练看到真实future、部署看到自生成future会产生分布偏移。", [("推理", "有/无visual CoT的VLA对照", "判断中间图像是否提升复杂任务"), ("规划", "future frame质量与动作成功率相关性", "避免只展示好看的个案"), ("消融", "CoT长度、attention和loss权重", "找出收益来自哪个环节")], "GR-1/2并行或交织预测未来与动作，CoT-VLA更明确规定‘先视觉推理、后动作’，因此可解释但延迟与误差链更长。", ["自生成visual goal可能不可达", "未来帧生成增加闭环延迟", "图像看似合理但缺少接触/力信息"], "We incorporate explicit visual chain-of-thought reasoning by predicting future image frames before actions."),
"c3ache": ("efficiency", "C3ache发现连续action chunk之间的residual存在跨chunk冗余，因此把缓存范围从单次去噪链扩展到相邻闭环推理。", ["记录标准WAM每个chunk与denoising step的中间residual。", "测量相邻chunk在不同层/时间步的相似性。", "建立cross-inference chunk cache并定义复用/刷新准则。", "在连续控制中复用计算，同时监控状态变化触发失效。"], "缓存本身不改变训练loss；可靠性取决于residual相似性估计。快速场景变化时必须回退完整计算。", [("加速", "端到端连续chunk latency", "不能只测单次denoising cache hit"), ("任务", "多种平滑与快速manipulation", "检查动作变化速度对命中率影响"), ("质量", "cache ratio—success Pareto", "确认复用不会积累陈旧预测")], "单chunk diffusion cache利用去噪步冗余，C3ache利用闭环chunk间冗余；Flash-WAM则通过蒸馏直接缩短去噪链。", ["突发接触/遮挡会让缓存立即过期", "错误复用可能跨chunk积累", "命中率依赖任务平滑度，不能外推所有操作"], "Our analysis reveals substantial redundancy across inference chunks."),
"flare": ("latent", "FLARE只给标准VLA增加少量future tokens和latent alignment loss，就让DiT policy在生成动作时预测未来观测表征，而不必解码像素视频。", ["视觉encoder得到当前与未来观测embedding。", "在VLA/DiT序列中加入learnable future tokens。", "动作感知future embedding model预测未来latent。", "与target future embedding对齐，同时训练action flow matching。"], "latent alignment与action loss共享主干；future target通常stop-gradient，避免encoder与predictor一起坍缩到常量。", [("仿真", "single-arm与humanoid multitask benchmarks", "覆盖不同本体和任务密度"), ("规模", "不同模型/数据规模", "检验轻量改动是否稳定可扩展"), ("消融", "future token数量、alignment和action conditioning", "定位implicit world modeling贡献")], "VLA-JEPA使用更完整JEPA/latent-action结构，FLARE追求最小架构改动；二者都牺牲可视像素未来，换取低成本latent rollout。", ["future latent难以解释或调试", "对齐可能只学可预测外观而非因果状态", "训练需要future observation，部署泛化仍受数据覆盖"], "FLARE integrates predictive latent world modeling into robot policy learning."),
"vbench-2": ("benchmark", "VBench-2.0从表面画质推进到intrinsic faithfulness，评估主体身份、时空组合、因果常识等长时一致性，而非只看单帧美学与平滑。", ["设计需要跨帧推理和实体绑定的新prompt集合。", "把intrinsic faithfulness拆成可诊断子维度。", "组合视觉模型、跟踪器与规则计算自动分数。", "通过human preference校准新维度和总分。"], "评测器要追踪同一实体与关系随时间的变化；单帧CLIP或简单光流不足以判断身份替换与因果错误。", [("维度", "多类intrinsic faithfulness", "比VBench原有表面维度更难"), ("模型", "主流开源与闭源video generators", "展示画质排名和内在一致排名可分离"), ("可靠性", "人工偏好分析", "检查自动metric是否真的测目标能力")], "VBench-2是通用视频生成诊断；WorldModelBench/VideoPhy把这些维度进一步聚焦到世界建模和物理应用。", ["自动检测器自身有误差与域偏差", "维度总分容易掩盖模型专长", "benchmark prompt可能被后续训练直接针对"], "Existing benchmarks mainly measure superficial faithfulness."),
"omnivta": ("multimodal", "OmniVTA用双流world model预测视觉与触觉未来，慢策略生成动作与参考触觉，60Hz快反射器再以预测—实测触觉差异纠偏。", ["同步编码多视角RGB、触觉图像与proprioception。", "双流DiT预测短时视觉latent与tactile latent。", "slow policy结合未来预测生成action chunk和触觉参考。", "fast reflex以60Hz读取触觉误差并输出residual action。"], "TactileVAE和future tactile prediction学习接触演化；fast controller的残差监督/控制目标决定预测能否真正提升执行。", [("数据", "OmniViTac 21k+轨迹、86任务、100+物体", "规模和交互机制覆盖是主要贡献之一"), ("闭环", "contact-rich真机任务", "比较无触觉、仅输入触觉和slow-fast完整系统"), ("扰动", "摩擦/位置/未见对象变化", "检验反射而非记忆固定动作")], "FAWAM用六轴wrench轨迹，OmniVTA用高维触觉图像与快反射；两者都让接触预测成为执行参考。", ["专用触觉硬件限制通用部署", "跨传感器域适配尚不自动", "60Hz残差和低频大模型的稳定性需联合调参"], "Contact-rich manipulation requires state transitions that cannot be reliably inferred from vision alone."),
"uwm": ("joint_diff", "UWM为video和action建立耦合扩散过程，在大规模机器人数据上共同预训练forward dynamics、inverse dynamics、policy与planner能力。", ["把视频latent与action trajectory映射到统一时间窗口。", "分别对两种模态加噪，保留各自统计尺度。", "共享Transformer通过cross-modal attention预测两条velocity/noise。", "通过不同条件mask切换policy、forward、inverse和planning任务。"], "多任务mask与coupled diffusion让同一模型学习多个条件分布；训练时要对不同任务和模态loss做平衡采样。", [("规模", "large robotic datasets联合预训练", "检查跨数据源和本体迁移"), ("任务", "policy/forward/inverse/planning多模式", "验证统一模型不是只在单一模式强"), ("消融", "decoupled vs coupled diffusion及pretrain/cotrain", "定位联合目标收益")], "PAD是joint denoising原型，UWM系统化统一多个条件分布；UVA重点解决video/action带宽与时间率不匹配。", ["任务mask组合带来训练复杂度", "两流loss易不平衡", "推理时完整视频采样可能不满足实时控制"], "Unified World Models couple video and action diffusion for pretraining on large robotic datasets."),
}


def deep_section(slug: str, data: tuple) -> str:
    group, thesis, stages, signal, evidence, compare, limits, quote = data
    g = GROUP[group]
    stage_rows = "".join(
        f"<tr><td>{i}</td><td>{escape(text)}</td><td>{escape(('输入与表示','核心变换','学习信号','闭环输出')[i-1])}</td></tr>"
        for i, text in enumerate(stages, 1)
    )
    evidence_rows = "".join(
        f"<tr><td>{escape(a)}</td><td>{escape(b)}</td><td>{escape(c)}</td></tr>" for a,b,c in evidence
    )
    checks = "".join(f"<li>{escape(x)}</li>" for x in g["checks"])
    limits_html = "".join(f"<li>{escape(x)}</li>" for x in limits)
    return f'''
<h2 id="paper-deep">逐篇深挖：把摘要主张还原成可执行流水线</h2>
<div class="cn-read"><div class="cn-label">这一节解决什么</div><p>前面的页面已经给出路线定位，但还没有把这篇论文自身的因果链拆到底。{escape(thesis)} {escape(g['bridge'])}</p></div>
<details class="en-quote"><summary>展开原文 · 摘要中的核心主张</summary><div class="quote-body"><p>“{escape(quote)}”</p><div class="quote-cite">— Abstract, PDF p.1</div></div></details>
<h3>四步信息流：每一步究竟改变什么</h3>
<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th>步</th><th>论文中的具体操作</th><th>阅读时追踪的变量</th></tr></thead><tbody>{stage_rows}</tbody></table>
<div class="cn-read"><div class="cn-label">训练信号怎么进入</div><p>{escape(signal)} {escape(g['signal'])}</p></div>

<h2 id="paper-evidence">实验精读：什么结果支持主张，什么结果不能越界解释</h2>
<div class="cn-read"><div class="cn-label">从方法走到证据</div><p>上一节说明了模块如何连接；这里把实验按“评测对象—设置—可归因结论”重排。读数时先固定数据、模型规模、推理预算与闭环协议，再比较最终结果。</p></div>
<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th>证据层</th><th>论文设置</th><th>能够支持的结论</th></tr></thead><tbody>{evidence_rows}</tbody></table>
<div class="callout blue"><div class="callout-label">和相邻路线怎样比较</div><p>{escape(compare)}</p></div>
<div class="quiz" data-correct="c" data-explain="只有同时控制基座、数据、推理预算和闭环评测，才能把性能差异较可靠地归因于这篇论文的核心机制。" data-explain-wrong="单看生成样例或最终成功率，都无法排除数据量和计算预算差异。"><div class="q-label">理解检查 · 实验归因</div><div class="q-text">复现或比较这篇工作时，哪组信息必须同时对齐？</div><div class="q-options"><button class="q-opt" data-k="a">作者单位和论文页数</button><button class="q-opt" data-k="b">只对齐最终成功率</button><button class="q-opt" data-k="c">基座、数据、推理预算和闭环协议</button><button class="q-opt" data-k="d">只对齐参数量</button></div><div class="q-feedback"></div></div>

<h2 id="paper-repro">复现与失效分析：先做哪些检查，哪里最可能坏</h2>
<div class="cn-read"><div class="cn-label">从论文结论回到工程</div><p>实验成立不代表换一个机器人或数据集仍自动成立。下面的清单把该路线最容易被忽略的实现变量显式列出；建议先复现最小消融，再扩到完整系统。</p></div>
<h3>最小复现清单</h3><ol style="color:var(--text2);line-height:1.85">{checks}</ol>
<h3>三个高概率失效点</h3><ul style="color:var(--text2);line-height:1.85">{limits_html}</ul>
<div class="callout red"><div class="callout-label">最终判断</div><p>{escape(thesis)} 只有当中间表示/生成、动作输出与闭环结果三条证据一致时，才能把它视为对 WAM 的实质推进。</p></div>
'''


def add_sidebar(html: str) -> str:
    links = '<a class="ds-leaf-top" href="#paper-deep">逐篇深挖</a><a class="ds-leaf-top" href="#paper-evidence">实验证据</a><a class="ds-leaf-top" href="#paper-repro">复现边界</a>'
    return html.replace('</aside>', links + '</aside>', 1)


for slug, data in P.items():
    path = ROOT / "papers" / f"{slug}.html"
    html = path.read_text()
    # Idempotent: replace our own section on subsequent runs.
    html = re.sub(r'\n?<h2 id="paper-deep">.*?(?=</main>)', '', html, flags=re.S)
    html = html.replace('<a class="ds-leaf-top" href="#paper-deep">逐篇深挖</a><a class="ds-leaf-top" href="#paper-evidence">实验证据</a><a class="ds-leaf-top" href="#paper-repro">复现边界</a>', '')
    html = add_sidebar(html)
    html = html.replace('</main>', deep_section(slug, data) + '</main>', 1)
    path.write_text(html)
    print(slug)

assert len(P) == 34, len(P)
